### ISSUE TITLE
Centralizace databázového připojení v aplikaci

### ISSUE THREAD

**Issue by DonSlon1** [F1l1pek/Nero#5]
### Centralizace databázového připojení v aplikaci

**Popis problému:**
V současné implementaci našeho projektu je kód pro připojení k databázi duplikován v mnoha souborech. Tento přístup je neefektivní a může vést k problémům při údržbě kódu, zejména pokud je potřeba změnit některé údaje pro připojení k databázi.

**Kód pro připojení:**
```php
$dbSpojeni = mysqli_connect("localhost", "root", null, "nero");
mysqli_set_charset($dbSpojeni, "UTF8");
```

**Návrh řešení:**
Je doporučeno vytvořit centralizovaný skript pro připojení k databázi, který bude použit ve všech souborech, kde je potřeba přístup k databázi. Tento skript bude obsahovat veškerou logiku pro připojení a inicializaci databázového spojení.

**Kroky k implementaci:**
1. Vytvořit soubor `db.php` v kořenovém adresáři nebo ve vhodném adresáři pro knihovny.
2. Přesunout kód pro připojení do souboru `db.php`.
3. V souboru `db.php` vytvořit funkci nebo inicializační blok pro navázání spojení.
4. Ve všech souborech, kde je potřeba databázové spojení, nahradit původní kód pro připojení vkládáním souboru `db.php` pomocí `require_once 'db.php';`.

**Příklad obsahu souboru `db.php`:**
```php
<?php
function connectToDB() {
    $dbSpojeni = mysqli_connect("localhost", "root", null, "nero");
    if (!$dbSpojeni) {
        die("Nelze se připojit k databázi: " . mysqli_connect_error());
    }
    mysqli_set_charset($dbSpojeni, "UTF8");
    return $dbSpojeni;
}
```

**Důvod zavedení:**
Centralizace databázového připojení zlepší údržbu kódu, zjednoduší změny konfigurace a zvýší bezpečnost tím, že se sníží riziko omylem zveřejněných přístupových údajů. Tímto způsobem bude možné lépe spravovat připojení k databázi a zabezpečení aplikace.

Prosím o revizi tohoto návrhu a jeho implementaci, aby byla zajištěna lepší správa a bezpečnost našich databázových operací.

Děkuji!

**Comment by zeruMELOUNcz** [comment]
hotvo
